# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildingBlockCreatorDialog
                                 A QGIS plugin
 This plugin combines ALKIS and ATKIS data to create building blocks semi-automatically.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lehmann, T., BRand, T.
        email                : t.brand@uni-muenster.de, t.lehmann@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import webbrowser

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'building_block_creator_dialog_base.ui'))


class BuildingBlockCreatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BuildingBlockCreatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def setupUi(self, BuildingBlockCreatorDialogBase):
        BuildingBlockCreatorDialogBase.setObjectName("BuildingBlockCreatorDialogBase")

        self.button_box = QtWidgets.QDialogButtonBox(BuildingBlockCreatorDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 320, 341, 32))
        font = QtGui.QFont()
        font.setKerning(True)
        self.button_box.setFont(font)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")

        self.verticalLayoutWidget = QtWidgets.QWidget(BuildingBlockCreatorDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 120, 361, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())

        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
       
        self.verticalLayout.addWidget(self.pushButton)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        
        self.label = QtWidgets.QLabel(BuildingBlockCreatorDialogBase)
        self.label.setGeometry(QtCore.QRect(30, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(BuildingBlockCreatorDialogBase)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 341, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(BuildingBlockCreatorDialogBase)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 320, 100, 31))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.on_about_clicked)
        
        # Connect main buttons
        self.pushButton.clicked.connect(self.on_building_blocks_clicked)
        self.pushButton_2.clicked.connect(self.on_road_details_clicked)

        self.retranslateUi(BuildingBlockCreatorDialogBase)
        self.button_box.accepted.connect(BuildingBlockCreatorDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(BuildingBlockCreatorDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BuildingBlockCreatorDialogBase)

    def retranslateUi(self, BuildingBlockCreatorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        BuildingBlockCreatorDialogBase.setWindowTitle(_translate("BuildingBlockCreatorDialogBase", "Building Block Creator"))
        self.pushButton.setText(_translate("BuildingBlockCreatorDialogBase", "Building Blocks"))
        self.pushButton_2.setText(_translate("BuildingBlockCreatorDialogBase", "Road Details"))
        self.label.setText(_translate("BuildingBlockCreatorDialogBase", "Building Block Creator"))
        self.label_2.setText(_translate("BuildingBlockCreatorDialogBase", "This plugin combines ALKIS and ATKIS data to create building blocks semi-automatically. The \"Road Details\" tool can be called separately."))
        self.pushButton_3.setToolTip(_translate("BuildingBlockCreatorDialogBase", "See the theoretical background"))
        self.pushButton_3.setText(_translate("BuildingBlockCreatorDialogBase", "About"))

    def on_about_clicked(self):
        """Handle About button click."""
        url = "https://github.com/tlehman1/Python_QGIS_ArcGIS_Uni_Muenster/blob/main/Exercise_13/2019-04-11-AbleitungVonBaubloecken_Kelm.pdf"
        webbrowser.open(url)
    
    def on_building_blocks_clicked(self):
        """Handle Building Blocks button click."""
        try:
            from .creator_dialog import CreatorDialog
            dialog = CreatorDialog(self)
            dialog.exec_()
        except Exception as e:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(self, "Error", f"Could not open Building Blocks dialog: {e}")
            
    def on_road_details_clicked(self):
        """Handle Road Details button click."""
        try:
            from .road_details_dialog import RoadDetailsDialog
            dialog = RoadDetailsDialog(self)
            dialog.exec_()
        except Exception as e:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(self, "Error", f"Could not open Road Details dialog: {e}")