# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'building_block_creator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuildingBlockCreatorDialogBase(object):
    def setupUi(self, BuildingBlockCreatorDialogBase):
        BuildingBlockCreatorDialogBase.setObjectName("BuildingBlockCreatorDialogBase")
        self.button_box = QtWidgets.QDialogButtonBox(BuildingBlockCreatorDialogBase)
        self.button_box.setGeometry(QtCore.QRect(50, 320, 341, 32))
        font = QtGui.QFont()
        font.setKerning(True)
        self.button_box.setFont(font)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(BuildingBlockCreatorDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 120, 361, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.label = QtWidgets.QLabel(BuildingBlockCreatorDialogBase)
        self.label.setGeometry(QtCore.QRect(30, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BuildingBlockCreatorDialogBase)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 341, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(BuildingBlockCreatorDialogBase)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 320, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.retranslateUi(BuildingBlockCreatorDialogBase)
        self.button_box.accepted.connect(BuildingBlockCreatorDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(BuildingBlockCreatorDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BuildingBlockCreatorDialogBase)

    def retranslateUi(self, BuildingBlockCreatorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        BuildingBlockCreatorDialogBase.setWindowTitle(_translate("BuildingBlockCreatorDialogBase", "Building Block Creator"))
        self.pushButton.setText(_translate("BuildingBlockCreatorDialogBase", "Generate Building Blocks"))
        self.label.setText(_translate("BuildingBlockCreatorDialogBase", "Building Block Creator"))
        self.label_2.setText(_translate("BuildingBlockCreatorDialogBase", "This plugin combines ALKIS and ATKIS data to create building blocks semi-automatically. The \"Collapse Road Detail\" tool can be called separatly."))
        self.pushButton_4.setText(_translate("BuildingBlockCreatorDialogBase", "Help"))
        self.pushButton_3.setToolTip(_translate("BuildingBlockCreatorDialogBase", "See the theoretical background"))
        self.pushButton_3.setText(_translate("BuildingBlockCreatorDialogBase", "About"))
