# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreatorDialog
                                 A QGIS plugin
 Dialog for creating building blocks from ALKIS/ATKIS data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lehmann, T., Brand, T.
        email                : t.brand@uni-muenster.de, t.lehmann@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry,
    QgsField, QgsFields, QgsWkbTypes, QgsProcessingException,
    QgsVectorFileWriter, QgsCoordinateReferenceSystem
)
from qgis.PyQt.QtCore import QVariant
import processing

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'building_block_creator_dialog_creator.ui'))


class CreatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(CreatorDialog, self).__init__(parent)
        self.setupUi(self)
        
        self.setup_layer_combos()
        
        # Connect help button
        self.helpButton.clicked.connect(self.on_help_clicked)
        
    def setup_layer_combos(self):
        """Setup the layer combo boxes with polygon layers only."""
        from qgis.core import QgsMapLayerProxyModel
        
        # Set filter to show only polygon layers
        self.communityLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.gemarkungLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        self.usageLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
    def accept(self):
        """Process building blocks creation when OK is clicked."""
        try:
            community_layer = self.communityLayerCombo.currentLayer()
            gemarkung_layer = self.gemarkungLayerCombo.currentLayer()
            usage_layer = self.usageLayerCombo.currentLayer()
            
            if not all([community_layer, gemarkung_layer, usage_layer]):
                QMessageBox.warning(
                    self, "Warning", 
                    "Please select all required layers:\n"
                    "- Municipal boundary\n"
                    "- District boundaries\n" 
                    "- Land use layer"
                )
                return
                
            output_name = self.outputNameEdit.text().strip()
            if not output_name:
                output_name = "building_blocks"
                
            result_layer = self.create_building_blocks(
                community_layer, gemarkung_layer, usage_layer, output_name
            )
            
            if result_layer and self.addToMapCheckBox.isChecked():
                QgsProject.instance().addMapLayer(result_layer)
                
            QMessageBox.information(
                self, "Success", 
                f"Building blocks created successfully as '{output_name}'"
            )
            
            super(CreatorDialog, self).accept()
            
        except Exception as e:
            QMessageBox.critical(
                self, "Error", 
                f"Failed to create building blocks: {str(e)}"
            )
            
    def create_building_blocks(self, community_layer, gemarkung_layer, usage_layer, output_name):
        """Create building blocks by combining the input layers."""
        try:
            # Use the CRS from the community layer
            crs = community_layer.crs()
            
            # Create memory layer for results
            result_layer = QgsVectorLayer(
                f"Polygon?crs={crs.authid()}", 
                output_name, 
                "memory"
            )
            
            # Create fields
            fields = QgsFields()
            fields.append(QgsField("block_id", QVariant.Int))
            fields.append(QgsField("community", QVariant.String))
            fields.append(QgsField("gemarkung", QVariant.String))
            fields.append(QgsField("usage_type", QVariant.String))
            fields.append(QgsField("area_sqm", QVariant.Double))
            
            result_layer.dataProvider().addAttributes(fields)
            result_layer.updateFields()
            
            result_layer.startEditing()
            
            block_id = 1
            
            # Process each community feature
            for community_feature in community_layer.getFeatures():
                community_geom = community_feature.geometry()
                community_name = self.get_feature_name(community_feature)
                
                # Find intersecting gemarkung features
                gemarkung_request = gemarkung_layer.getFeatures()
                for gemarkung_feature in gemarkung_request:
                    gemarkung_geom = gemarkung_feature.geometry()
                    
                    # Check intersection with community
                    if not community_geom.intersects(gemarkung_geom):
                        continue
                        
                    gemarkung_name = self.get_feature_name(gemarkung_feature)
                    intersection_geom = community_geom.intersection(gemarkung_geom)
                    
                    # Find usage features within this intersection
                    usage_request = usage_layer.getFeatures()
                    for usage_feature in usage_request:
                        usage_geom = usage_feature.geometry()
                        
                        # Check intersection with community-gemarkung area
                        if not intersection_geom.intersects(usage_geom):
                            continue
                            
                        usage_type = self.get_feature_usage_type(usage_feature)
                        
                        # Create the building block geometry
                        block_geom = intersection_geom.intersection(usage_geom)
                        
                        if block_geom.isNull() or block_geom.isEmpty():
                            continue
                            
                        # Calculate area
                        area = block_geom.area()
                        
                        # Create new feature
                        new_feature = QgsFeature(result_layer.fields())
                        new_feature.setGeometry(block_geom)
                        new_feature.setAttribute("block_id", block_id)
                        new_feature.setAttribute("community", community_name)
                        new_feature.setAttribute("gemarkung", gemarkung_name)
                        new_feature.setAttribute("usage_type", usage_type)
                        new_feature.setAttribute("area_sqm", area)
                        
                        result_layer.dataProvider().addFeature(new_feature)
                        block_id += 1
                        
            result_layer.commitChanges()
            result_layer.updateExtents()
            
            return result_layer
            
        except Exception as e:
            raise QgsProcessingException(f"Error creating building blocks: {str(e)}")
            
    def get_feature_name(self, feature):
        """Extract a name from a feature, trying common field names."""
        name_fields = ['name', 'Name', 'NAME', 'bezeichnung', 'Bezeichnung', 'label']
        
        for field_name in name_fields:
            if field_name in [field.name() for field in feature.fields()]:
                value = feature.attribute(field_name)
                if value and str(value).strip():
                    return str(value)
                    
        # Fallback to feature ID
        return f"Feature_{feature.id()}"
        
    def get_feature_usage_type(self, feature):
        """Extract usage type from a feature."""
        usage_fields = ['nutzung', 'Nutzung', 'usage', 'type', 'Type', 'art', 'Art']
        
        for field_name in usage_fields:
            if field_name in [field.name() for field in feature.fields()]:
                value = feature.attribute(field_name)
                if value and str(value).strip():
                    return str(value)
                    
        return "Unknown"
        
    def on_help_clicked(self):
        """Handle Help button click."""
        try:
            from .building_blocks_help_dialog import BuildingBlocksHelpDialog
            help_dialog = BuildingBlocksHelpDialog(self)
            help_dialog.exec_()
        except Exception as e:
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(self, "Error", f"Could not open Help dialog: {e}")