# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadDetailsDialog
                                 A QGIS plugin
 Dialog for creating center lines from road polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lehmann, T., Brand, T.
        email                : t.brand@uni-muenster.de, t.lehmann@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry, 
    QgsField, QgsFields, QgsWkbTypes, QgsProcessingException,
    QgsVectorFileWriter, QgsCoordinateReferenceSystem
)
from qgis.PyQt.QtCore import QVariant
import processing

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'road_details_dialog.ui'))


class RoadDetailsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(RoadDetailsDialog, self).__init__(parent)
        self.setupUi(self)
        
        self.setup_layer_combo()
        
        # Connect help button
        self.helpButton.clicked.connect(self.on_help_clicked)
        
    def setup_layer_combo(self):
        """Setup the layer combo box with polygon layers only."""
        from qgis.core import QgsMapLayerProxyModel
        
        # Set filter to show only polygon layers
        self.usageLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
        # Set placeholder text
        self.usageLayerCombo.setCurrentText("Select layer")
        
    def accept(self):
        """Process the center line creation when OK is clicked."""
        try:
            selected_layer = self.usageLayerCombo.currentLayer()
            
            if not selected_layer:
                QMessageBox.warning(self, "Warning", "Please select a usage layer.")
                return
                
            buffer_distance = self.bufferSpinBox.value()
            output_name = self.outputNameEdit.text().strip()
            
            if not output_name:
                output_name = "road_center_lines"
                
            # Create center lines
            result_layer = self.create_center_lines(
                selected_layer, buffer_distance, output_name
            )
            
            if result_layer and self.addToMapCheckBox.isChecked():
                QgsProject.instance().addMapLayer(result_layer)
                
            QMessageBox.information(
                self, "Success", 
                f"Center lines created successfully as '{output_name}'"
            )
            
            super(RoadDetailsDialog, self).accept()
            
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to create center lines: {str(e)}")
            
    def create_center_lines(self, input_layer, buffer_distance, output_name):
        """Create center lines from polygon features."""
        try:
            # Create a memory layer for the result
            crs = input_layer.crs()
            result_layer = QgsVectorLayer(
                f"LineString?crs={crs.authid()}", 
                output_name, 
                "memory"
            )
            
            # Copy fields from input layer
            result_layer.dataProvider().addAttributes(input_layer.fields())
            result_layer.updateFields()
            
            result_layer.startEditing()
            
            for feature in input_layer.getFeatures():
                geom = feature.geometry()
                
                if geom.isNull() or geom.isEmpty():
                    continue
                    
                # Create center line using polygon centroid approach
                center_line = self.polygon_to_centerline(geom, buffer_distance)
                
                if center_line and not center_line.isNull():
                    # Create new feature
                    new_feature = QgsFeature(result_layer.fields())
                    new_feature.setGeometry(center_line)
                    
                    # Copy attributes
                    for field_idx in range(len(input_layer.fields())):
                        new_feature.setAttribute(field_idx, feature.attribute(field_idx))
                        
                    result_layer.dataProvider().addFeature(new_feature)
                    
            result_layer.commitChanges()
            result_layer.updateExtents()
            
            return result_layer
            
        except Exception as e:
            raise QgsProcessingException(f"Error creating center lines: {str(e)}")
            
    def polygon_to_centerline(self, polygon_geom, buffer_distance):
        """Convert polygon to center line using medial axis approximation."""
        try:
            # Get the polygon boundary
            boundary = polygon_geom.boundary()
            
            # Create buffer inward to get approximate medial axis
            inward_buffer = polygon_geom.buffer(-buffer_distance)
            
            if inward_buffer.isNull() or inward_buffer.isEmpty():
                # If buffer is too large, use centroid-based approach
                centroid = polygon_geom.centroid()
                bounds = polygon_geom.boundingBox()
                
                # Create a simple line through the centroid
                if bounds.width() > bounds.height():
                    # Horizontal line
                    start_point = QgsGeometry.fromPointXY(
                        QgsPointXY(bounds.xMinimum(), centroid.asPoint().y())
                    )
                    end_point = QgsGeometry.fromPointXY(
                        QgsPointXY(bounds.xMaximum(), centroid.asPoint().y())
                    )
                else:
                    # Vertical line
                    start_point = QgsGeometry.fromPointXY(
                        QgsPointXY(centroid.asPoint().x(), bounds.yMinimum())
                    )
                    end_point = QgsGeometry.fromPointXY(
                        QgsPointXY(centroid.asPoint().x(), bounds.yMaximum())
                    )
                
                center_line = start_point.shortestLine(end_point)
                return center_line.intersection(polygon_geom)
            
            # Get the skeleton/medial axis from the buffered polygon
            if inward_buffer.type() == QgsWkbTypes.PolygonGeometry:
                # Convert to line by getting the boundary and then simplifying
                medial_boundary = inward_buffer.boundary()
                
                # Simplify to get main axis
                simplified = medial_boundary.simplify(buffer_distance / 2)
                
                if simplified.type() == QgsWkbTypes.LineGeometry:
                    return simplified
                    
            # Fallback: create line from centroid extending along major axis
            centroid = polygon_geom.centroid()
            bounds = polygon_geom.boundingBox()
            
            # Determine major axis direction
            if bounds.width() > bounds.height():
                # Horizontal orientation
                length = bounds.width() * 0.8
                start_x = centroid.asPoint().x() - length / 2
                end_x = centroid.asPoint().x() + length / 2
                y = centroid.asPoint().y()
                
                line_geom = QgsGeometry.fromPolylineXY([
                    QgsPointXY(start_x, y),
                    QgsPointXY(end_x, y)
                ])
            else:
                # Vertical orientation  
                length = bounds.height() * 0.8
                x = centroid.asPoint().x()
                start_y = centroid.asPoint().y() - length / 2
                end_y = centroid.asPoint().y() + length / 2
                
                line_geom = QgsGeometry.fromPolylineXY([
                    QgsPointXY(x, start_y),
                    QgsPointXY(x, end_y)
                ])
            
            # Clip line to polygon boundary
            clipped = line_geom.intersection(polygon_geom)
            return clipped
            
        except Exception as e:
            # Return a simple centroid-based line as fallback
            centroid = polygon_geom.centroid()
            bounds = polygon_geom.boundingBox()
            
            # Create minimal line at centroid
            point = centroid.asPoint()
            small_line = QgsGeometry.fromPolylineXY([
                QgsPointXY(point.x() - 0.1, point.y()),
                QgsPointXY(point.x() + 0.1, point.y())
            ])
            
            return small_line
            
    def on_help_clicked(self):
        """Handle Help button click."""
        try:
            from .road_details_help_dialog import RoadDetailsHelpDialog
            help_dialog = RoadDetailsHelpDialog(self)
            help_dialog.exec_()
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not open Help dialog: {e}")