# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadDetailsHelpDialog
                                 A QGIS plugin
 Help dialog for the Road Details center line creation functionality
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lehmann, T., Brand, T.
        email                : t.brand@uni-muenster.de, t.lehmann@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic, QtWidgets

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'road_details_help_dialog.ui'))


class RoadDetailsHelpDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(RoadDetailsHelpDialog, self).__init__(parent)
        self.setupUi(self)