# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoadDetailsDialog
                                 A QGIS plugin
 Dialog for creating center lines from road polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Lehmann, T., Brand, T.
        email                : t.brand@uni-muenster.de, t.lehmann@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox, QProgressDialog
from qgis.PyQt.QtCore import Qt
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsFeature, QgsGeometry, 
    QgsField, QgsFields, QgsWkbTypes, QgsProcessingException,
    QgsVectorFileWriter, QgsCoordinateReferenceSystem, QgsPointXY
)
from qgis.PyQt.QtCore import QVariant
import processing

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'road_details_dialog.ui'))


class RoadDetailsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(RoadDetailsDialog, self).__init__(parent)
        self.setupUi(self)
        
        self.setup_layer_combo()
        
        # Connect help button
        self.helpButton.clicked.connect(self.on_help_clicked)
        
    def setup_layer_combo(self):
        """Setup the layer combo box with polygon layers only."""
        from qgis.core import QgsMapLayerProxyModel
        
        # Set filter to show only polygon layers
        self.usageLayerCombo.setFilters(QgsMapLayerProxyModel.PolygonLayer)
        
        # Allow null selection (empty field)
        self.usageLayerCombo.setAllowEmptyLayer(True)
        
        # Set to empty initially
        self.usageLayerCombo.setCurrentIndex(-1)
        
        # Auto-select nutzungFlurstueck layer if available
        self.auto_select_usage_layer()
    
    def auto_select_usage_layer(self):
        """Auto-select nutzungFlurstueck layer if it is loaded."""
        project = QgsProject.instance()
        
        # Search for nutzungFlurstueck layer
        for layer in project.mapLayers().values():
            if layer.name() == 'nutzungFlurstueck':
                self.usageLayerCombo.setLayer(layer)
                print(f"Debug: Auto-selected layer 'nutzungFlurstueck' in Road Details dialog")
                break
        
    def accept(self):
        """Process the center line creation when OK is clicked."""
        try:
            selected_layer = self.usageLayerCombo.currentLayer()
            
            if not selected_layer:
                QMessageBox.warning(self, "Warning", "Please select a usage layer.")
                return
                
            buffer_distance = self.bufferSpinBox.value()
            output_name = self.outputNameEdit.text().strip()
            
            if not output_name:
                output_name = "road_centerlines"
            
            # Create and show progress dialog
            progress = QProgressDialog("Processing road centerlines...", "Cancel", 0, 100, self)
            progress.setWindowModality(Qt.WindowModal)
            progress.setWindowTitle("Processing")
            progress.show()
                
            # Filter, dissolve and create centerlines
            result_layer = self.create_center_lines(
                selected_layer, buffer_distance, output_name, progress
            )
            
            progress.close()
            
            if result_layer and self.addToMapCheckBox.isChecked():
                QgsProject.instance().addMapLayer(result_layer)
                
            QMessageBox.information(
                self, "Success", 
                f"Buffered roads created successfully as '{output_name}' with {buffer_distance}m buffer"
            )
            
            super(RoadDetailsDialog, self).accept()
            
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to create center lines: {str(e)}")
            
    def create_center_lines(self, input_layer, buffer_distance, output_name, progress=None):
        """Filter, dissolve and create centerlines from 'Weg' and 'Straßenverkehr' features."""
        try:
            if progress:
                progress.setLabelText("Step 1: Filtering road features...")
                progress.setValue(10)
                QtWidgets.QApplication.processEvents()
            
            # Step 1: Filter features for road types
            filtered_features = self.filter_road_features(input_layer, progress)
            
            if not filtered_features:
                raise QgsProcessingException("No road features found with usage types 'Weg' or 'Straßenverkehr'")
            
            if progress:
                progress.setLabelText("Step 2: Creating dissolved geometries...")
                progress.setValue(30)
                QtWidgets.QApplication.processEvents()
            
            # Step 2: Dissolve/Union the filtered geometries
            dissolved_geometry = self.dissolve_road_features(filtered_features, progress)
            
            if not dissolved_geometry or dissolved_geometry.isNull():
                raise QgsProcessingException("Failed to dissolve road geometries")
            
            if progress:
                progress.setLabelText("Step 3: Creating centerlines...")
                progress.setValue(60)
                QtWidgets.QApplication.processEvents()
            
            # Step 3: Create centerlines from dissolved geometry
            centerlines = self.create_centerlines_from_dissolved(dissolved_geometry, buffer_distance, progress)
            
            if not centerlines:
                raise QgsProcessingException("Failed to create centerlines from dissolved geometry")
            
            if progress:
                progress.setLabelText("Step 4: Applying buffer to centerlines...")
                progress.setValue(80)
                QtWidgets.QApplication.processEvents()
            
            # Step 4: Apply buffer to centerlines to create road polygons
            buffered_roads = self.apply_buffer_to_centerlines(centerlines, buffer_distance, progress)
            
            if progress:
                progress.setLabelText("Step 5: Building result layer...")
                progress.setValue(90)
                QtWidgets.QApplication.processEvents()
            
            # Step 5: Create result layer with buffered roads
            result_layer = self.build_buffered_road_layer(buffered_roads, input_layer.crs(), output_name, buffer_distance)
            
            if progress:
                progress.setValue(100)
                QtWidgets.QApplication.processEvents()
            
            print(f"Debug: Created {len(buffered_roads)} buffered roads from {len(filtered_features)} filtered features")
            return result_layer
            
        except Exception as e:
            raise QgsProcessingException(f"Error creating centerlines: {str(e)}")
    
    def dissolve_road_features(self, filtered_features, progress=None):
        """Dissolve/Union all filtered road features into single geometry."""
        try:
            if not filtered_features:
                return None
            
            # Start with first geometry
            dissolved_geom = filtered_features[0].geometry()
            
            # Union with all other geometries
            for i, feature in enumerate(filtered_features[1:], 1):
                if progress and i % 10 == 0:
                    progress_value = 30 + int((i / len(filtered_features)) * 20)
                    progress.setValue(progress_value)
                    progress.setLabelText(f"Dissolving geometry {i}/{len(filtered_features)}")
                    QtWidgets.QApplication.processEvents()
                
                geom = feature.geometry()
                if geom and not geom.isNull():
                    dissolved_geom = dissolved_geom.combine(geom)
            
            print(f"Debug: Dissolved {len(filtered_features)} features into single geometry")
            return dissolved_geom
            
        except Exception as e:
            print(f"Debug: Error in dissolve_road_features: {e}")
            return None
    
    def create_centerlines_from_dissolved(self, dissolved_geometry, buffer_distance, progress=None):
        """Create centerlines from dissolved geometry using QGIS skeleton algorithm."""
        centerlines = []
        
        try:
            # Handle multipart geometry
            if dissolved_geometry.isMultipart():
                if dissolved_geometry.type() == QgsWkbTypes.PolygonGeometry:
                    multipolygon = dissolved_geometry.asMultiPolygon()
                    for i, polygon in enumerate(multipolygon):
                        if progress:
                            progress_value = 60 + int((i / len(multipolygon)) * 15)
                            progress.setValue(progress_value)
                            progress.setLabelText(f"Processing polygon {i+1}/{len(multipolygon)}")
                            QtWidgets.QApplication.processEvents()
                        
                        if polygon:
                            single_geom = QgsGeometry.fromPolygonXY(polygon)
                            skeleton_lines = self.compute_skeleton_for_polygon(single_geom)
                            centerlines.extend(skeleton_lines)
            else:
                # Single part geometry
                skeleton_lines = self.compute_skeleton_for_polygon(dissolved_geometry)
                centerlines.extend(skeleton_lines)
            
            print(f"Debug: Created {len(centerlines)} centerlines from dissolved geometry")
            return centerlines
            
        except Exception as e:
            print(f"Debug: Error in create_centerlines_from_dissolved: {e}")
            return []
    
    def compute_skeleton_for_polygon(self, polygon_geom):
        """Compute skeleton lines for a single polygon using QGIS processing."""
        skeleton_lines = []
        
        try:
            # Create temporary layer with the polygon
            temp_layer = QgsVectorLayer("Polygon", "temp_polygon", "memory")
            temp_layer.dataProvider().addAttributes([QgsField("id", QVariant.Int)])
            temp_layer.updateFields()
            temp_layer.startEditing()
            
            feature = QgsFeature(temp_layer.fields())
            feature.setGeometry(polygon_geom)
            feature.setAttribute("id", 1)
            temp_layer.dataProvider().addFeature(feature)
            temp_layer.commitChanges()
            
            # Use QGIS processing to compute the polygon skeleton
            result = processing.run(
                "qgis:polygonskeleton",
                {
                    'INPUT': temp_layer,
                    'OUTPUT': 'TEMPORARY_OUTPUT'
                }
            )
            
            # Extract skeleton lines from the result
            skeleton_layer = result['OUTPUT']
            for feature in skeleton_layer.getFeatures():
                skeleton_geom = feature.geometry()
                if skeleton_geom and not skeleton_geom.isNull():
                    skeleton_lines.append(skeleton_geom)
                    
        except Exception as e:
            print(f"Debug: QGIS skeleton algorithm failed: {e}")
            # Fallback to simple centerline
            fallback_line = self.create_simple_centerline(polygon_geom)
            if fallback_line:
                skeleton_lines.append(fallback_line)
            
        return skeleton_lines
    
    def create_simple_centerline(self, polygon_geom):
        """Create simple centerline as fallback."""
        try:
            bounds = polygon_geom.boundingBox()
            centroid = polygon_geom.centroid().asPoint()
            
            if bounds.width() > bounds.height():
                # Horizontal line
                line_geom = QgsGeometry.fromPolylineXY([
                    QgsPointXY(bounds.xMinimum() + bounds.width() * 0.05, centroid.y()),
                    QgsPointXY(bounds.xMaximum() - bounds.width() * 0.05, centroid.y())
                ])
            else:
                # Vertical line
                line_geom = QgsGeometry.fromPolylineXY([
                    QgsPointXY(centroid.x(), bounds.yMinimum() + bounds.height() * 0.05),
                    QgsPointXY(centroid.x(), bounds.yMaximum() - bounds.height() * 0.05)
                ])
            
            return line_geom
            
        except Exception as e:
            print(f"Debug: Error in create_simple_centerline: {e}")
            return None
    
    def apply_buffer_to_centerlines(self, centerlines, buffer_distance, progress=None):
        """Apply buffer to centerlines to create road polygons."""
        buffered_roads = []
        
        try:
            for i, centerline in enumerate(centerlines):
                if progress and i % 5 == 0:
                    progress_value = 80 + int((i / len(centerlines)) * 8)
                    progress.setValue(progress_value)
                    progress.setLabelText(f"Buffering centerline {i+1}/{len(centerlines)}")
                    QtWidgets.QApplication.processEvents()
                
                if centerline and not centerline.isNull():
                    # Apply buffer to create road polygon
                    buffered = centerline.buffer(buffer_distance, segments=8)
                    if buffered and not buffered.isNull():
                        buffered_roads.append({
                            'geometry': buffered,
                            'centerline': centerline,
                            'length': centerline.length()
                        })
            
            print(f"Debug: Applied {buffer_distance}m buffer to {len(centerlines)} centerlines")
            return buffered_roads
            
        except Exception as e:
            print(f"Debug: Error in apply_buffer_to_centerlines: {e}")
            return []
    
    def build_buffered_road_layer(self, buffered_roads, crs, output_name, buffer_distance):
        """Build the final buffered road layer."""
        try:
            result_layer = QgsVectorLayer(
                f"Polygon?crs={crs.authid()}", 
                output_name, 
                "memory"
            )
            
            # Add fields
            fields = QgsFields()
            fields.append(QgsField("road_id", QVariant.Int))
            fields.append(QgsField("length_m", QVariant.Double))
            fields.append(QgsField("area_sqm", QVariant.Double))
            fields.append(QgsField("buffer_m", QVariant.Double))
            fields.append(QgsField("type", QVariant.String))
            
            result_layer.dataProvider().addAttributes(fields)
            result_layer.updateFields()
            result_layer.startEditing()
            
            # Add buffered roads as features
            road_id = 1
            for road_data in buffered_roads:
                buffered_geom = road_data['geometry']
                length = road_data['length']
                
                if buffered_geom and not buffered_geom.isNull():
                    feature = QgsFeature(result_layer.fields())
                    feature.setGeometry(buffered_geom)
                    feature.setAttribute("road_id", road_id)
                    feature.setAttribute("length_m", length)
                    feature.setAttribute("area_sqm", buffered_geom.area())
                    feature.setAttribute("buffer_m", buffer_distance)
                    feature.setAttribute("type", "buffered_road")
                    
                    result_layer.dataProvider().addFeature(feature)
                    road_id += 1
            
            result_layer.commitChanges()
            result_layer.updateExtents()
            
            print(f"Debug: Created buffered road layer with {road_id-1} features")
            return result_layer
            
        except Exception as e:
            print(f"Debug: Error in build_buffered_road_layer: {e}")
            return None
    
    def build_centerline_layer(self, centerlines, crs, output_name):
        """Build the final centerline layer."""
        try:
            result_layer = QgsVectorLayer(
                f"LineString?crs={crs.authid()}", 
                output_name, 
                "memory"
            )
            
            # Add fields
            fields = QgsFields()
            fields.append(QgsField("line_id", QVariant.Int))
            fields.append(QgsField("length_m", QVariant.Double))
            fields.append(QgsField("type", QVariant.String))
            
            result_layer.dataProvider().addAttributes(fields)
            result_layer.updateFields()
            result_layer.startEditing()
            
            # Add centerlines as features
            line_id = 1
            for centerline in centerlines:
                if centerline and not centerline.isNull():
                    feature = QgsFeature(result_layer.fields())
                    feature.setGeometry(centerline)
                    feature.setAttribute("line_id", line_id)
                    feature.setAttribute("length_m", centerline.length())
                    feature.setAttribute("type", "road_centerline")
                    
                    result_layer.dataProvider().addFeature(feature)
                    line_id += 1
            
            result_layer.commitChanges()
            result_layer.updateExtents()
            
            return result_layer
            
        except Exception as e:
            print(f"Debug: Error in build_centerline_layer: {e}")
            return None
    
    def filter_road_features(self, input_layer, progress=None):
        """Filter features for road types ('Weg' and 'Straßenverkehr')."""
        allowed_usage_types = {'Weg', 'Straßenverkehr'}
        filtered_features = []
        
        total_features = input_layer.featureCount()
        processed = 0
        
        for feature in input_layer.getFeatures():
            processed += 1
            if progress and processed % 100 == 0:
                progress_value = 10 + int((processed / total_features) * 15)  # 10-25%
                progress.setValue(progress_value)
                progress.setLabelText(f"Filtering... {processed}/{total_features}")
                QtWidgets.QApplication.processEvents()
            
            usage_type = self.get_feature_usage_type(feature)
            if usage_type and usage_type in allowed_usage_types:
                filtered_features.append(feature)
        
        print(f"Debug: Found {len(filtered_features)} road features out of {total_features} total")
        return filtered_features
    
    def get_feature_usage_type(self, feature):
        """Extract usage type from a feature."""
        usage_fields = ['nutzart', 'Nutzart', 'NUTZART', 'nutzung', 'Nutzung', 'usage', 'type', 'Type', 'art', 'Art']
        
        for field_name in usage_fields:
            if field_name in [field.name() for field in feature.fields()]:
                value = feature.attribute(field_name)
                if value and str(value).strip():
                    return str(value).strip()
        
        return None
            
    def on_help_clicked(self):
        """Handle Help button click."""
        try:
            from .road_details_help_dialog import RoadDetailsHelpDialog
            help_dialog = RoadDetailsHelpDialog(self)
            help_dialog.exec_()
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not open Help dialog: {e}")