# -*- coding: utf-8 -*-
"""
/***************************************************************************
 muensterCityDistrictTools
                                 A QGIS plugin
 Plugin containing tools to analyze city districts of Muenster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-12
        copyright            : (C) 2025 by Tim Lehmann, Tobias Brand
        email                : t.brand@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load muensterCityDistrictTools class from file muensterCityDistrictTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .city_tools import muensterCityDistrictTools
    return muensterCityDistrictTools(iface)
