# -*- coding: utf-8 -*-
"""
/***************************************************************************
 muensterCityDistrictToolsDialog
                                 A QGIS plugin
 Plugin containing tools to analyze city districts of Muenster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-12
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tim Lehmann, Tobias Brand
        email                : t.brand@uni-muenster.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .city_tools_dialog_export import Ui_exportDialog
from .city_tools_dialog_query import Ui_queryDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'city_tools_dialog_base.ui'))


class muensterCityDistrictToolsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(muensterCityDistrictToolsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.export_data.clicked.connect(self.openExportDialog)
        self.query_data.clicked.connect(self.openQueryDialog)

    def openExportDialog(self):
        exportDialog = QtWidgets.QDialog()
        ui = Ui_exportDialog()
        ui.setupUi(exportDialog)
        exportDialog.exec_()
    
    def openQueryDialog(self):
        queryDialog = QtWidgets.QDialog()
        ui = Ui_queryDialog()
        ui.setupUi(queryDialog)
        queryDialog.exec_()

