# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'city_tools_dialog_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exportDialog(object):
    def setupUi(self, exportDialog):
        exportDialog.setObjectName("exportDialog")
        exportDialog.resize(461, 352)
        self.buttonBox = QtWidgets.QDialogButtonBox(exportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(exportDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.export_csv = QtWidgets.QPushButton(exportDialog)
        self.export_csv.setGeometry(QtCore.QRect(100, 100, 251, 51))
        self.export_csv.setObjectName("export_csv")
        self.export_pdf = QtWidgets.QPushButton(exportDialog)
        self.export_pdf.setGeometry(QtCore.QRect(100, 170, 251, 51))
        self.export_pdf.setObjectName("export_pdf")

        self.retranslateUi(exportDialog)
        self.buttonBox.accepted.connect(exportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(exportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(exportDialog)

    def retranslateUi(self, exportDialog):
        _translate = QtCore.QCoreApplication.translate
        exportDialog.setWindowTitle(_translate("exportDialog", "Dialog"))
        self.label.setText(_translate("exportDialog", "Export Data"))
        self.export_csv.setText(_translate("exportDialog", "Export as *.csv"))
        self.export_pdf.setText(_translate("exportDialog", "Export as *.pdf"))
