# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'city_tools_dialog_query.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_queryDialog(object):
    def setupUi(self, queryDialog):
        queryDialog.setObjectName("queryDialog")
        queryDialog.resize(458, 349)
        self.buttonBox = QtWidgets.QDialogButtonBox(queryDialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(queryDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(queryDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 56, 291, 20))
        self.label_2.setObjectName("label_2")
        self.query_result_label = QtWidgets.QLabel(queryDialog)
        self.query_result_label.setGeometry(QtCore.QRect(30, 80, 281, 171))
        self.query_result_label.setText("")
        self.query_result_label.setObjectName("query_result_label")

        self.retranslateUi(queryDialog)
        self.buttonBox.accepted.connect(queryDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(queryDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(queryDialog)

    def retranslateUi(self, queryDialog):
        _translate = QtCore.QCoreApplication.translate
        queryDialog.setWindowTitle(_translate("queryDialog", "Dialog"))
        self.label.setText(_translate("queryDialog", "Query Result"))
        self.label_2.setText(_translate("queryDialog", "The query was successful! These are the results:"))
